apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-server
spec:
  replicas: 1  # Initial number of replicas
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: my-server
        image: nginx:1.14.2
        ports:
        - containerPort: 80