apiVersion: v1
kind: Service
metadata:
  name: my-service-loadbalancer
spec:
  selector:
    app: my-loadbalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  